### PR TITLE
Doc: Replace cross-doc links with attributes

### PR DESCRIPTION
**Pull request by karenzone**
Replaces cross-doc links to shared attributes.
Asciidoc formatting cleanup.

### CODE REVIEW

**Comment by karenzone** [comment]
@jsvd  This plugin is deprecated.  I made the needed docs changes, just in case we do need to bump version and republish again some time in the future. I believe that the version comparison changes you are making to the script will make this approach acceptable.  Please validate or dispute my logic. Thanks!

**Comment by jsvd** [comment]
@karenzone we'll be able to see these changes in the documentation of logstash per release with the current code, where we always replace the docs on the right `logstash-docs/{branch}`

For the versioned docs we won't see this change, but I think that's ok for now as no one will be looking for this particular plugin in the versioned docs

**Review by jsvd — APPROVED** [review]
LGTM

**Comment by karenzone** [comment]
> For the versioned docs we won't see this change, but I think that's ok for now as no one will be looking for this particular plugin in the versioned docs

That's what I was hoping for. Thanks for confirming.

**Pull request merged**
