### PR TITLE
Add support for PROXY protocol

### PR DESCRIPTION
**Pull request by jordansissel**
Forked continuation of #34.

### CODE REVIEW

**Comment by jordansissel** [comment]
@nneul I've restructured some of the tests from #34 and things are passing now for me.

**Comment by jordansissel** [comment]
(Caveat, this PR will only likely work against Logstash 5.2 or master branches because Logstash 5.1.1 doesn't have https://github.com/elastic/logstash/pull/6309)

**Comment by nneul** [comment]
----
@nneul did you intend to have this not set proxy_host or proxy_port fields? The TCP input does this :

https://github.com/logstash-plugins/logstash-input-tcp/blob/master/lib/logstash/inputs/tcp.rb#L183-L188
----

No, that was not an intentional exclusion. Simple enough to add.

**Comment by jordansissel** [comment]
@nneul ok cool, I will add it.

**Comment by jordansissel** [comment]
This PR is blocked until Logstash 5.2 is released. Logstash 5.0 and 5.1 both have a bug [fixed in 5.2 branch](https://github.com/elastic/logstash/pull/6309).

**Comment by nneul** [comment]
@jordansissel Any update on merging this as it looks like 5.2.1 was already released?

**Comment by jordansissel** [comment]
@nneul This is on my todo list for after I recover from Elasticon and this week's meetings.

**Comment by jordansissel** [comment]
Woo, CI passing.

**Comment by ph** [comment]
@whack LGTM, Can you update the changelog + bumping the version?

One of the build job on travis was failling, It was a bundler caching issue, after clearing the cache everything went green!

**Comment by nneul** [comment]
Anything else that needs to be done before this can be merged?

**Comment by jordansissel** [comment]
I will publish this as a plugin soon. I have some new work I need to add to this plugin before publishing.

**Pull request closed without merging**
